# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'child.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Child(object):
    def setupUi(self, Child):
        Child.setObjectName("Child")
        Child.resize(400, 300)
        self.m_btnChild = QtWidgets.QPushButton(Child)
        self.m_btnChild.setGeometry(QtCore.QRect(90, 140, 92, 28))
        self.m_btnChild.setObjectName("m_btnChild")
        self.m_childlineEdit = QtWidgets.QLineEdit(Child)
        self.m_childlineEdit.setGeometry(QtCore.QRect(80, 90, 113, 21))
        self.m_childlineEdit.setObjectName("m_childlineEdit")

        self.retranslateUi(Child)
        QtCore.QMetaObject.connectSlotsByName(Child)

    def retranslateUi(self, Child):
        _translate = QtCore.QCoreApplication.translate
        Child.setWindowTitle(_translate("Child", "Form"))
        self.m_btnChild.setText(_translate("Child", "关闭子窗口"))
