# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.m_btnMain = QtWidgets.QPushButton(Form)
        self.m_btnMain.setGeometry(QtCore.QRect(50, 30, 92, 28))
        self.m_btnMain.setObjectName("m_btnMain")
        self.m_showText = QtWidgets.QLineEdit(Form)
        self.m_showText.setGeometry(QtCore.QRect(30, 130, 181, 21))
        self.m_showText.setObjectName("m_showText")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.m_btnMain.setText(_translate("Form", "打开子窗口"))
