# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'twodim.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Two_Dim(object):
    def setupUi(self, Two_Dim):
        Two_Dim.setObjectName("Two_Dim")
        Two_Dim.resize(415, 138)
        self.widget = QtWidgets.QWidget(Two_Dim)
        self.widget.setGeometry(QtCore.QRect(11, 11, 391, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Box_two_x = QtWidgets.QComboBox(self.widget)
        self.Box_two_x.setObjectName("Box_two_x")
        self.horizontalLayout.addWidget(self.Box_two_x)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Box_two_y = QtWidgets.QComboBox(self.widget)
        self.Box_two_y.setObjectName("Box_two_y")
        self.horizontalLayout.addWidget(self.Box_two_y)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_two = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_two.setObjectName("lineEdit_two")
        self.horizontalLayout_2.addWidget(self.lineEdit_two)
        self.btn_two_choose = QtWidgets.QPushButton(self.widget)
        self.btn_two_choose.setObjectName("btn_two_choose")
        self.horizontalLayout_2.addWidget(self.btn_two_choose)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_two_run = QtWidgets.QPushButton(self.widget)
        self.btn_two_run.setObjectName("btn_two_run")
        self.horizontalLayout_3.addWidget(self.btn_two_run)
        self.btn_two_close = QtWidgets.QPushButton(self.widget)
        self.btn_two_close.setObjectName("btn_two_close")
        self.horizontalLayout_3.addWidget(self.btn_two_close)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Two_Dim)
        QtCore.QMetaObject.connectSlotsByName(Two_Dim)

    def retranslateUi(self, Two_Dim):
        _translate = QtCore.QCoreApplication.translate
        Two_Dim.setWindowTitle(_translate("Two_Dim", "Form"))
        self.label.setText(_translate("Two_Dim", "x轴:"))
        self.label_2.setText(_translate("Two_Dim", "y轴:"))
        self.btn_two_choose.setText(_translate("Two_Dim", "选择文件"))
        self.btn_two_run.setText(_translate("Two_Dim", "运行"))
        self.btn_two_close.setText(_translate("Two_Dim", "退出"))
